name: Style tests (flake8)

on:
  push:
    branches:
      - master
  pull_request:
    # Run workflow when PR is changed, or when changed from draft to ready
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'

jobs:

  build-and-test:
    name: Style
    runs-on: ubuntu-latest

    # Skip job if it's a draft PR
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: install pints
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          python -m pip install .[dev]

      - name: run style tests
        run: |
          python -m flake8
